<a href="https://colab.research.google.com/github/Hbada/Numpy-lessons-notebook/blob/master/Numpy_practice_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# original notebook source: Google Colab
# exercise sources: Udemy course Python for Data Science... by Portilla
import numpy as np

## Create array and slices

In [0]:
# create array from 1 to 5
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [9]:
# create array from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
# create array 10 to 50, every 2nd number (evens)
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
# create array 10 to 50, odds only
np.arange(11,51,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [53]:
# slice from index 2 up to but not including 4
arr[2:4]

array([3, 4])

In [56]:
# "broadcast" the value 35 into array at index 0 and 1
arr[0:2] = 35
arr

array([35, 35,  3,  4,  5])

In [0]:
# re-create array of 5 elements
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [0]:
# create 5 random numbers between 0 and 5
rand_arr = np.random.rand(5)
rand_arr # results are different every time this cell is run

array([0.90649338, 0.37105352, 0.81437113, 0.33438675, 0.12652438])

In [18]:
# create 5 random numbers from normal distribution
rand_norm_arr = np.random.randn(5)
rand_norm_arr

array([-0.78812176,  0.96553072, -0.9714828 , -1.204266  , -1.63038695])

In [69]:
# create evenly spaced numbers over a range
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [52]:
# more complex array of evenly spaced numbers over an interval
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [37]:
# create array of 5 one's
ones_arr = np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

## Max and min

In [0]:
# create array of 25 random numbers from normal distribution
rand_norm_arr = np.random.randn(25)
rand_norm_arr

array([ 1.43205485, -0.55812372, -0.68455624, -1.41662653,  1.26904729,
       -0.10079617, -0.06484557,  0.52735273, -0.40155089,  1.00229872,
       -1.1776841 ,  1.01573834,  2.30981847, -1.88907446, -0.83726486,
       -0.61645002, -0.54331498,  1.08397415, -1.19401095,  1.23306596,
       -0.40221001,  0.55070226, -0.22999488, -0.20076187,  0.24140577])

In [57]:
# calculate min value
rand_norm_arr.min()

-1.630386954009459

In [0]:
rand_norm_arr.max() # calculate max value

2.7793173967822775

In [0]:
rand_norm_arr.argmax() # retrieve index of the max value 

16

In [0]:
rand_norm_arr.argmin() # retrieve index of min

13

## Create matrix aka 2D array

In [72]:
# create a nested array using python
arr_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [73]:
# create 2D array, aka matrix
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
# retrieve shape of the array
arr_2d.shape

(3, 3)

In [75]:
# easier way to make a matrix of sequential numbers
# new matrix with 3 rows of 3 incl. zero
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# create 5 by 5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Matrix index selections

In [77]:
# show matrix again
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
# select one row - the first one
arr_2d[0]

array([1, 2, 3])

In [80]:
# select last row
arr_2d[-1] # could also use arr_2d[2]

array([7, 8, 9])

In [84]:
# select more than one row from a large matrix
arr_2d[1:3] # also valid: arr_2d[1:3,:] for row 1 to 2, all columns

array([[4, 5, 6],
       [7, 8, 9]])

In [85]:
# select 2nd row, 2nd column
arr_2d[1][1]

5

In [87]:
arr_2d[2,2] # another format to select single item, at row 3, col 3

9

In [88]:
# select up to but not including row 2, and columns from 1 on
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

## Comparison operators

In [66]:
# display original 1D array
arr

array([35, 35,  3,  4,  5])

In [0]:
# calculate whether any items are greater than 3
arr > 3

array([False, False, False,  True,  True])

In [0]:
# save boolean results of a comparison
bool_array = arr > 2
bool_array

array([False, False,  True,  True,  True])

In [0]:
# show the elements in arr where bool_array = True
arr[bool_array]

array([3, 4, 5])

In [0]:
# another way to collect elements that are true for a comparison
arr[arr < 3]

array([1, 2])

In [67]:
# create matrix 0 to 50; 5 rows & 10 elements each
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
# select row 4 & 5, index 3 to 4 only
arr_2d[3:, 3:5]

array([[33, 34],
       [43, 44]])

In [0]:
# select middle row, # 3
arr_2d[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Array operations

In [0]:
arr_2d + arr_2d

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [34]:
# new random normal distribution array
randn_arr = np.random.randn(9).reshape(3,3)
randn_arr

array([[-1.99938432,  0.07718552, -0.41701054],
       [-1.31664305, -0.73286689,  0.76526646],
       [-0.63060353, -0.362207  ,  0.55869405]])

In [35]:
# scalar operation applied to all elements
randn_arr = randn_arr * 3
randn_arr

array([[-5.99815296,  0.23155656, -1.25103163],
       [-3.94992916, -2.19860068,  2.29579939],
       [-1.89181059, -1.08662101,  1.67608214]])

In [36]:
# return floor of each element
np.floor(randn_arr)

array([[-6.,  0., -2.],
       [-4., -3.,  2.],
       [-2., -2.,  1.]])

In [38]:
# multiply all by 3
ones_arr * 3

array([3., 3., 3., 3., 3.])

In [39]:
# create array of 5 zero elements
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [40]:
zeros_arr / zeros_arr # divide 0 by 0 gives null values

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan])

In [41]:
1 / zeros_arr # different error, gives infinity values

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf])

## Universal array functions

In [46]:
arr = np.arange(1,6) # new array 1 to 5
arr

array([1, 2, 3, 4, 5])

In [0]:
arr_sq = arr ** 2 # square of every element
arr_sq

array([ 1,  4,  9, 16, 25])

In [0]:
np.sqrt(arr_sq) # square root of each element in arr_sq

array([1., 2., 3., 4., 5.])

In [0]:
np.sqrt(49) # square root of a number

7.0

In [0]:
# calculate exponential of each element; Euler's formula
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

More info:

1. Exponential function
https://en.wikipedia.org/wiki/Exponential_function
1. Euler's formula https://en.wikipedia.org/wiki/Euler%27s_formula

In [0]:
# find max using np instead of arr.max() shown earlier
np.max(arr)

5

In [0]:
np.sin(arr) # calculate sin of each element

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [0]:
np.log(arr) # calculate log of each element

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

More info:

1. Documentation for universal functions in numpy https://docs.scipy.org/doc/numpy/reference/ufuncs.html. Scroll down near the end to find list

In [93]:
# recall earlier array
arr

array([35, 35,  3,  4,  5])

In [94]:
# sum the elements using .sum()
arr.sum()

82

In [95]:
# sum the elements using np.sum()
np.sum(arr) # also works for matrix

82

In [96]:
# calculate standard deviation
np.std(arr)

15.200000000000001

In [99]:
# recall an earlier bigger matrix
randn_arr

array([[-5.99815296,  0.23155656, -1.25103163],
       [-3.94992916, -2.19860068,  2.29579939],
       [-1.89181059, -1.08662101,  1.67608214]])

In [100]:
# another way to get SD
randn_arr.std()

2.458728055260157

In [101]:
# recall matrix from earlier
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
# sum the columns
arr_2d.sum(axis=0)

array([12, 15, 18])