<a href="https://colab.research.google.com/github/Hbada/Numpy-lessons-notebook/blob/master/Numpy_practice_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## Create array and slices

In [0]:
arr = np.arange(1,6) # create array from 1 to 5
arr

array([1, 2, 3, 4, 5])

In [0]:
arr[2:4] # slice from index 2 up to but not including 4

array([3, 4])

In [0]:
arr[0:2] = 35 # "broadcast" the value 35 into array at index 0 and 1
arr

array([35, 35,  3,  4,  5])

In [0]:
arr = np.arange(1,6) # re-create array of 5 elements
arr

array([1, 2, 3, 4, 5])

In [0]:
rand_arr = np.random.rand(5) # create 5 random numbers between 0 and 5
rand_arr # results are different every time this cell is run

array([0.90649338, 0.37105352, 0.81437113, 0.33438675, 0.12652438])

## Max and min

In [0]:
rand_norm_arr = np.random.randn(25) # create array of 25 random numbers from normal distribution
rand_norm_arr

array([ 1.43205485, -0.55812372, -0.68455624, -1.41662653,  1.26904729,
       -0.10079617, -0.06484557,  0.52735273, -0.40155089,  1.00229872,
       -1.1776841 ,  1.01573834,  2.30981847, -1.88907446, -0.83726486,
       -0.61645002, -0.54331498,  1.08397415, -1.19401095,  1.23306596,
       -0.40221001,  0.55070226, -0.22999488, -0.20076187,  0.24140577])

In [0]:
rand_norm_arr.min() # calculate min value

-1.9632940959824894

In [0]:
rand_norm_arr.max() # calculate max value

2.7793173967822775

In [0]:
rand_norm_arr.argmax() # retrieve index of the max value 

16

In [0]:
rand_norm_arr.argmin() # retrieve index of min

13

## Create matrix aka 2D array

In [0]:
arr_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # create a nested array using python
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 2D array, aka matrix
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
arr_2d.shape # retrieve shape of the array

(5, 10)

## Matrix index selections

In [0]:
arr_2d[1][1] # select 2nd row, 2nd column

5

In [0]:
arr_2d[0] # select entire first item of array, which is a whole 'row' of elements

array([1, 2, 3])

In [0]:
arr_2d[2,2] # another way to select row 3, item 3

9

In [0]:
arr_2d[:2, 1:] # select up to but not including row 2, and columns from 1 on

array([[2, 3],
       [5, 6]])

## Comparison operators

In [0]:
arr # original 1D array

array([1, 2, 3, 4, 5])

In [0]:
arr > 3 # calculate whether any items are greater than 3

array([False, False, False,  True,  True])

In [0]:
bool_array = arr > 2 # save boolean results of a comparison
bool_array

array([False, False,  True,  True,  True])

In [0]:
arr[bool_array] # show the elements in arr where bool_array = True

array([3, 4, 5])

In [0]:
arr[arr < 3] # another way to collect elements that are true for a comparison

array([1, 2])

In [0]:
arr_2d = np.arange(50).reshape(5,10) # create matrix 0 to 50; 5 rows & 10 elements each
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
arr_2d[3:, 3:5] # select row 4 & 5, index 3 to 4 only

array([[33, 34],
       [43, 44]])

In [0]:
arr_2d[2] # select middle row, # 3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Array operations

In [0]:
arr_2d + arr_2d

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [0]:
rand_norm_arr # random normal distribution elements from earlier

array([ 1.43205485, -0.55812372, -0.68455624, -1.41662653,  1.26904729,
       -0.10079617, -0.06484557,  0.52735273, -0.40155089,  1.00229872,
       -1.1776841 ,  1.01573834,  2.30981847, -1.88907446, -0.83726486,
       -0.61645002, -0.54331498,  1.08397415, -1.19401095,  1.23306596,
       -0.40221001,  0.55070226, -0.22999488, -0.20076187,  0.24140577])

In [0]:
norm_arr_2 = rand_norm_arr * 3 # scalar operation applied to all elements
norm_arr_2

array([ 4.29616454, -1.67437116, -2.05366873, -4.2498796 ,  3.80714186,
       -0.30238851, -0.19453672,  1.5820582 , -1.20465268,  3.00689617,
       -3.53305231,  3.04721502,  6.92945542, -5.66722339, -2.51179457,
       -1.84935007, -1.62994495,  3.25192246, -3.58203284,  3.69919788,
       -1.20663002,  1.65210678, -0.68998463, -0.6022856 ,  0.7242173 ])

In [0]:
np.floor(norm_arr_2).reshape(5,5) # return floor of each element & reshape as 5 rows & 5 col

array([[ 4., -2., -3., -5.,  3.],
       [-1., -1.,  1., -2.,  3.],
       [-4.,  3.,  6., -6., -3.],
       [-2., -2.,  3., -4.,  3.],
       [-2.,  1., -1., -1.,  0.]])

In [0]:
zero_arr = np.zeros(5) # create array of 5 zero elements
zero_arr

array([0., 0., 0., 0., 0.])

In [0]:
zero_arr / zero_arr # divide 0 by 0 gives null values

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan])

In [0]:
1 / zero_arr # different error, gives infinity values

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf])

## Universal array functions

In [0]:
arr # show matrix again

array([1, 2, 3, 4, 5])

In [0]:
arr_sq = arr ** 2 # square of every element
arr_sq

array([ 1,  4,  9, 16, 25])

In [0]:
np.sqrt(arr_sq) # square root of each element in arr_sq

array([1., 2., 3., 4., 5.])

In [0]:
np.sqrt(49) # square root of a number

7.0

In [0]:
np.exp(arr) # calculate exponential of each element; Euler's formula

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

More info:

1. Exponential function
https://en.wikipedia.org/wiki/Exponential_function
1. Euler's formula https://en.wikipedia.org/wiki/Euler%27s_formula

In [0]:
np.max(arr) # find max using np instead of arr.max() shown earlier

5

In [0]:
np.sin(arr) # calculate sin of each element

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [0]:
np.log(arr) # calculate log of each element

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

More info:

1. Documentation for universal functions in numpy https://docs.scipy.org/doc/numpy/reference/ufuncs.html. Scroll down near the end to find list