In [1]:
import numpy as np

In [5]:
arr = np.arange(1,6) # create array from 1 to 5
arr

array([1, 2, 3, 4, 5])

In [6]:
arr[2:4] # slice from index 2 up to but not including 4

array([3, 4])

In [7]:
arr[0:2] = 35 # "broadcast" the value 35 into array at index 0 and 1
arr

array([35, 35,  3,  4,  5])

In [9]:
arr = np.arange(1,6) # re-create array of 5 elements
arr

array([1, 2, 3, 4, 5])